// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['rpc']['Client']['Close']();
}

export function Connect() {
  return window['go']['rpc']['Client']['Connect']();
}

export function SetActivity(arg1) {
  return window['go']['rpc']['Client']['SetActivity'](arg1);
}

export function SetUserVoiceSettings(arg1) {
  return window['go']['rpc']['Client']['SetUserVoiceSettings'](arg1);
}
