// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {rpc} from '../models';

export function Close():Promise<void>;

export function Connect():Promise<Error>;

export function SetActivity(arg1:rpc.Activity):Promise<Error>;

export function SetUserVoiceSettings(arg1:rpc.SetUserVoiceSettingsCommandArgs):Promise<Error>;
