// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccessToken() {
  return window['go']['app']['App']['GetAccessToken']();
}

export function SetAccessToken(arg1) {
  return window['go']['app']['App']['SetAccessToken'](arg1);
}
