name: main-deploy
on:
    push:
        branches:
            - "main"
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "20.x"
                  registry-url: "https://registry.npmjs.org"

            - uses: pnpm/action-setup@v2.0.1
              id: pnpm-install
              with:
                  version: 8
                  run_install: false

            - name: Install Deps
              run: pnpm i

            - name: Build
              run: pnpm build
              env:
                  VITE_YOUTUBE_API_BASE_URL: ${{ secrets.VITE_YOUTUBE_API_BASE_URL }}
                  VITE_OAUTH_URL: ${{ secrets.VITE_OAUTH_URL }}
                  VITE_APPLICATIONS: ${{ secrets.VITE_APPLICATIONS }}
                  VITE_YT_IMAGE_PROXY: ${{ secrets.VITE_YT_IMAGE_PROXY }}
                  VITE_SPOTIFY_INTEGRATION: ${{ secrets.VITE_SPOTIFY_INTEGRATION }}
                  VITE_DISCORD_ACTIVITY_URL_MAPPINGS: ${{ secrets.VITE_DISCORD_ACTIVITY_URL_MAPPINGS }}
                  VITE_LAVALINK_FILTER_PLUGINS: ${{ secrets.VITE_LAVALINK_FILTER_PLUGINS }}

            - name: Deploy
              uses: wangyucode/sftp-upload-action@v1.4.8
              with:
                  localDir: ./dist/
                  exclude: "**/*.png" # TODO fix this, slows down upload: https://github.com/wangyucode/sftp-upload-action/issues/11
                  host: ${{ secrets.FTP_HOST }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  remoteDir: ${{ secrets.VOLUME_PATH }}
                  removeExtraFilesOnServer: true
                  dryRun: false

            - name: Purge cache
              uses: jakejarvis/cloudflare-purge-action@master
              env:
                  CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
                  CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
    create-release:
        needs: deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Get version
              id: package
              run: echo "::set-output name=version::$(jq -r .version package.json)"
            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ steps.package.outputs.version }}
                  name: Release ${{ steps.package.outputs.version }}
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
